"""create_cultivation_profiles_table

Revision ID: 5761773a45e6
Revises: ac8f397b3fae
Create Date: 2026-06-06 22:07:29.280898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5761773a45e6'
down_revision: Union[str, None] = 'ac8f397b3fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivation_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('realm', sa.String(), nullable=False),
    sa.Column('realm_stage', sa.String(), nullable=True),
    sa.Column('cultivation_power', sa.Integer(), nullable=False),
    sa.Column('spirit_energy', sa.Integer(), nullable=False),
    sa.Column('max_spirit_energy', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultivation_profiles_user_id'), 'cultivation_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cultivation_profiles_user_id'), table_name='cultivation_profiles')
    op.drop_table('cultivation_profiles')
    # ### end Alembic commands ###
