"""create_vocabulary_tables

Revision ID: 723cd506ac9b
Revises: 5761773a45e6
Create Date: 2026-06-06 22:22:26.440129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723cd506ac9b'
down_revision: Union[str, None] = '5761773a45e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('required_realm', sa.String(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_sets_code'), 'vocabulary_sets', ['code'], unique=True)
    op.create_table('vocabulary_words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('english', sa.String(), nullable=False),
    sa.Column('vietnamese', sa.String(), nullable=False),
    sa.Column('pronunciation', sa.String(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['vocabulary_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_words_set_id'), 'vocabulary_words', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_words_set_id'), table_name='vocabulary_words')
    op.drop_table('vocabulary_words')
    op.drop_index(op.f('ix_vocabulary_sets_code'), table_name='vocabulary_sets')
    op.drop_table('vocabulary_sets')
    # ### end Alembic commands ###
