"""create_user_word_progress_table

Revision ID: 9bb7ab2791a9
Revises: 723cd506ac9b
Create Date: 2026-06-06 22:38:41.972022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb7ab2791a9'
down_revision: Union[str, None] = '723cd506ac9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_word_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('last_answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_progress')
    )
    op.create_index(op.f('ix_user_word_progress_user_id'), 'user_word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_word_progress_word_id'), 'user_word_progress', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_word_progress_word_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_user_id'), table_name='user_word_progress')
    op.drop_table('user_word_progress')
    # ### end Alembic commands ###
