"""create_quest_tables

Revision ID: d3084290565b
Revises: 9bb7ab2791a9
Create Date: 2026-06-06 23:43:19.163201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3084290565b'
down_revision: Union[str, None] = '9bb7ab2791a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_mission_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission_type', sa.String(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_cultivation_power', sa.Integer(), nullable=False),
    sa.Column('reward_reputation', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_mission_definitions_code'), 'daily_mission_definitions', ['code'], unique=True)
    op.create_table('user_daily_mission_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('progress_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('progress_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['daily_mission_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_id', 'progress_date', name='uq_user_mission_date')
    )
    op.create_index(op.f('ix_user_daily_mission_progress_mission_id'), 'user_daily_mission_progress', ['mission_id'], unique=False)
    op.create_index(op.f('ix_user_daily_mission_progress_progress_date'), 'user_daily_mission_progress', ['progress_date'], unique=False)
    op.create_index(op.f('ix_user_daily_mission_progress_user_id'), 'user_daily_mission_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_mission_progress_user_id'), table_name='user_daily_mission_progress')
    op.drop_index(op.f('ix_user_daily_mission_progress_progress_date'), table_name='user_daily_mission_progress')
    op.drop_index(op.f('ix_user_daily_mission_progress_mission_id'), table_name='user_daily_mission_progress')
    op.drop_table('user_daily_mission_progress')
    op.drop_index(op.f('ix_daily_mission_definitions_code'), table_name='daily_mission_definitions')
    op.drop_table('daily_mission_definitions')
    # ### end Alembic commands ###
